version: "3"
services:
  react-app:
    build: ./front
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - br0
  node-app:
    build: ./backend
    ports:
      - "3003:3003"
    depends_on:
      - mongo
    restart: always
    networks: 
      - br0
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    restart: always
    networks:
      - br0
    volumes:
      - mongo_volume:/data/db
networks:
  br0:
    driver: bridge
volumes:
   mongo_volume:
     driver: local


